title: Website

tabs: 
  content: 
    label: Content
    icon: folder
    sections: 
      contentA:
        type: pages
        headline: Pages
        image: false
  seo: 
    extends: tabs/seo
    columns: 
      left:
        sections:
          seoA:
            fields:
              imageSEO:
                query: site.images